machine:
  services:
    - docker

dependencies:
  override:
    - docker build -t docker98k/nginx-php .

    # Do basic test in `dependencies` section - it doesn't make to continue if it fails here
    - docker run -d --name nginx docker98k/nginx-php
    - docker logs -f nginx > ${CIRCLE_ARTIFACTS}/docker-nginx.log:
        background: true
    - sleep 3
    - docker logs nginx | grep "nginx entered RUNNING state"
    - docker rm -f nginx || true

# Run tests
test:
  override:
    # Launch it
    - docker run -d -p 8080:80 --name nginx --env="NGINX_GENERATE_DEFAULT_VHOST=true" docker98k/nginx-php
    - while true; do if docker logs nginx | grep "nginx entered RUNNING state"; then break; else sleep 1; fi done
    - curl -Ssi http://localhost:8080
    - curl -Ssi http://localhost:8080 | grep '200 OK'

    # Check phpinfo page (we have it because NGINX_GENERATE_DEFAULT_VHOST is set)
    - curl -Ssi http://localhost:8080 | grep 'PHP Version 7'

    # Check if custom php.ini directives are applied
    - curl -Ssi http://localhost:8080 | grep memory_limit | grep 512M

    # Check if we have PECL extensions installed / loaded
    - curl -Ssi http://localhost:8080 | grep 'Redis Version'

    # Check if PHP is available in PATH
    - docker run -ti docker98k/nginx-php "php -v"
    - docker run -ti docker98k/nginx-php "php -i"

    # Check if we have common dev tools working
    - docker run -ti docker98k/nginx-php "mysql --version"
    - docker run -ti docker98k/nginx-php "git --version"
    - docker run -ti docker98k/nginx-php "ruby -v"
    - docker run -ti docker98k/nginx-php "gem -v"
    - docker run -ti docker98k/nginx-php "nvm --version"
    - docker run -ti docker98k/nginx-php "node -v"
    - docker run -ti docker98k/nginx-php "npm -v"
    - docker run -ti docker98k/nginx-php "grunt --version"
    - docker run -ti docker98k/nginx-php "gulp -v"
    - docker rm -f nginx || true

    # Check if status page for PHP-FPM is working
    - docker run -d -p 80:80 --name nginx --env="NGINX_GENERATE_DEFAULT_VHOST=true" docker98k/nginx-php
    - while true; do if docker logs nginx | grep "nginx entered RUNNING state"; then break; else sleep 1; fi done
    - curl -Ssi http://localhost/fpm_status | grep "HTTP/1.1 403 Forbidden"
    - docker rm -f nginx || true

    - docker run -d -p 80:80 --name nginx --env="NGINX_GENERATE_DEFAULT_VHOST=true" --env="STATUS_PAGE_ALLOWED_IP=$(ip -4 addr show docker0 | grep inet | cut -d/ -f1 | awk '{print $2}')" docker98k/nginx-php
    - while true; do if docker logs nginx | grep "nginx entered RUNNING state"; then break; else sleep 1; fi done
    - curl -Ssi http://localhost/fpm_status
    - curl -Ssi http://localhost/fpm_status | grep "HTTP/1.1 200 OK"
    - curl -Ssi http://localhost/fpm_status | grep "start time"
