version: "3.1"
services:
  web:
    image: docker98k/google-mirror
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8011:80"
    networks:
      - webnet
networks:
  webnet:
