kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jira-data
spec:
  accessModes:
   - "ReadWriteOnce"
  resources:
    requests:
       storage: "100Gi"  
  storageClassName: "hangzhou-b-ssd"