apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 'docker98k/openresty:1.13.6.1'
        imagePullPolicy: Always
        ports:
        - containerPort: 80
